language: node_js
node_js:
  - "18"

dist: focal

branches:
  only:
    - master
    - main

before_install:
  # Install required tools
  - sudo apt-get update && sudo apt-get install -y jq
  - pip install --user awscli
  - npm install -g npm@9.8.1

  # Configure AWS
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION

  # Assume role
  - |
    CREDENTIALS=$(aws sts assume-role \
      --role-arn $AWS_ROLE_ARN \
      --role-session-name "TravisDeployment" \
      --duration-seconds 900)
  - export AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r .Credentials.AccessKeyId)
  - export AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r .Credentials.SecretAccessKey)
  - export AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r .Credentials.SessionToken)

install:
  - npm ci

script:
  - echo "Starting deployment..."

deploy:
  provider: script
  script: |
    aws s3 sync . s3://jesseclark.io \
      --delete \
      --acl public-read \
      --exclude ".git/*" \
      --exclude "node_modules/*" \
      --exclude ".env" \
      --exclude ".travis.yml" \
      --exclude "test-deploy.sh"
  cleanup: false
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$ && $TRAVIS_PULL_REQUEST = false

after_deploy:
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

notifications:
  email:
    recipients:
      - jesseclark@duck.com
    on_success: change
    on_failure: always

env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
    - CLOUDFRONT_DISTRIBUTION_ID=E1JFX2AF0IL1RM
    - AWS_ROLE_ARN=arn:aws:iam::500194254701:role/email-from-lambda-role
