language: node_js
node_js:
  - "18"

# Specify Ubuntu 20.04 (Focal Fossa)
dist: focal

# Allow both main and master branches
branches:
  only:
    - master
    - main

before_install:
  # Update system packages
  - sudo apt-get update
  # Remove any existing npm config
  - rm -f .npmrc
  - rm -rf ~/.npm
  # Clear npm cache
  - npm cache clean --force
  # Install npm and serverless
  - npm install -g npm@9.8.1
  - npm install -g serverless@3

install:
  - npm ci

before_script:
  - echo "Checking build status..."
  - npm run build || true

script:
  - echo "Starting deployment process..."
  - serverless package

deploy:
  # S3 Deployment
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: jesseclark.io
    region: us-east-1
    skip_cleanup: true
    local_dir: .
    acl: public-read
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|main)$ && $TRAVIS_PULL_REQUEST = false

  # API Deployment
  - provider: script
    script: serverless deploy
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|main)$ && $TRAVIS_PULL_REQUEST = false

after_success:
  - echo "Build completed successfully"

after_failure:
  - echo "Build failed"

notifications:
  email:
    recipients:
      - jesseclark@duck.com
    on_success: change
    on_failure: always

env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
