language: node_js
node_js:
  - "16"

# Safelist
branches:
  only:
    - main

before_install:
  - rm -f .npmrc
  - npm cache clean --force
  - npm install -g npm@latest
  - npm install -g serverless

install:
  - echo "Installing dependencies..."
  - npm ci

cache:
  npm: true
  directories:
    - node_modules
    - ~/.npm

before_script:
  - echo "Starting deployment..."

script:
  - echo "Deploying to AWS..."

deploy:
  # Deploy static files to S3
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: jesseclark.io
    region: us-east-1
    skip_cleanup: true
    local_dir: .
    acl: public-read
    on:
      branch: main

  # Deploy API Gateway/Lambda via Serverless
  - provider: script
    script: serverless deploy
    skip_cleanup: true
    on:
      branch: main

after_deploy:
  - echo "Deployed successfully to jesseclark.io"

notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
