language: node_js
node_js:
  - "16"

cache:
  directories:
    - node_modules

script:
  - echo "Deploying to GitHub Pages..."

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
  local_dir: .
  fqdn: jesseclark.io
